=== AMP2563/EXAMEN-11-05-20205/ejercicio1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="expediente">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="estado" type="xs:string" />
                <xs:element name="periodo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inicio" type="xs:string" />
                            <xs:element name="fin" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cliente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dni" type="xs:string" />
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="direcion" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="procuradores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="procurador">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dni" type="xs:string" />
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="direccion" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="idExpediente" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AMP2563/EXAMEN-11-05-20205/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>


<expediente xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ejercicio1.xsd" idExpediente="EXP2025-001">
    <estado>en tramite</estado>
    <periodo>
        <inicio>2025-01-15</inicio>
        <fin>2025-03-20</fin>
    </periodo>
    <cliente>
        <dni>12345678A</dni>
        <nombre>Juan Pérez</nombre>
        <direcion>Calle del Pez, 4</direcion>
    </cliente>
    <procuradores>
        <procurador>
            <dni>87654321B</dni>
            <nombre>Ana López</nombre>
            <direccion>Juagado de Guardia, 3</direccion>
        </procurador>
    </procuradores>
</expediente>
